In [1]:
import pandas as pd
import numpy as np
import polars as pl

In [2]:
from cricket_tables import build_cricket_tables

tables = build_cricket_tables()
matches = tables["matches"]
deliveries = tables["deliveries"]

In [13]:
matches.select("scheduled_overs").unique()

shape: (2, 1)
┌─────────────────┐
│ scheduled_overs │
│ ---             │
│ f64             │
╞═════════════════╡
│ 20.0            │
│ 50.0            │
└─────────────────┘

In [14]:
deliveries.head()

shape: (5, 23)
┌──────────┬────────────┬────────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ match_id ┆ innings_nu ┆ batting_te ┆ over_numb ┆ … ┆ penalty ┆ is_legal_ ┆ is_wicket ┆ wickets_o │
│ ---      ┆ mber       ┆ am         ┆ er        ┆   ┆ ---     ┆ delivery  ┆ ---       ┆ n_deliver │
│ str      ┆ ---        ┆ ---        ┆ ---       ┆   ┆ i64     ┆ ---       ┆ bool      ┆ y         │
│          ┆ i64        ┆ str        ┆ i64       ┆   ┆         ┆ bool      ┆           ┆ ---       │
│          ┆            ┆            ┆           ┆   ┆         ┆           ┆           ┆ i64       │
╞══════════╪════════════╪════════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ 1001349  ┆ 1          ┆ Australia  ┆ 0         ┆ … ┆ 0       ┆ true      ┆ false     ┆ 0         │
│ 1001349  ┆ 1          ┆ Australia  ┆ 0         ┆ … ┆ 0       ┆ true      ┆ false     ┆ 0         │
│ 1001349  ┆ 1          ┆ Australia  ┆ 0         ┆ … ┆ 0       ┆ true      ┆ false     ┆ 0         │
│ 1001349  ┆ 1          ┆ Australia  ┆ 0         ┆ … ┆ 0       ┆ true      ┆ false     ┆ 0         │
│ 1001349  ┆ 1          ┆ Australia  ┆ 0         ┆ … ┆ 0       ┆ true      ┆ false     ┆ 0         │
└──────────┴────────────┴────────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [3]:
matches.head()

shape: (5, 23)
┌──────────┬────────────┬─────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ match_id ┆ start_date ┆ season  ┆ balls_per_ ┆ … ┆ outcome_m ┆ win_by_ru ┆ win_by_wi ┆ player_of │
│ ---      ┆ ---        ┆ ---     ┆ over       ┆   ┆ ethod     ┆ ns        ┆ ckets     ┆ _match    │
│ str      ┆ str        ┆ str     ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆            ┆         ┆ i64        ┆   ┆ str       ┆ i64       ┆ i64       ┆ str       │
╞══════════╪════════════╪═════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1001349  ┆ 2017-02-17 ┆ 2016/17 ┆ 6          ┆ … ┆ null      ┆ null      ┆ 5         ┆ DAS       │
│          ┆            ┆         ┆            ┆   ┆           ┆           ┆           ┆ Gunaratne │
│ 1001351  ┆ 2017-02-19 ┆ 2016/17 ┆ 6          ┆ … ┆ null      ┆ null      ┆ 2         ┆ DAS       │
│          ┆            ┆         ┆            ┆   ┆           ┆           ┆           ┆ Gunaratne │
│ 1001353  ┆ 2017-02-22 ┆ 2016/17 ┆ 6          ┆ … ┆ null      ┆ 41        ┆ null      ┆ A Zampa   │
│ 1004729  ┆ 2016-09-05 ┆ 2016    ┆ 6          ┆ … ┆ null      ┆ 40        ┆ null      ┆ null      │
│ 1007655  ┆ 2016-06-18 ┆ 2016    ┆ 6          ┆ … ┆ null      ┆ 2         ┆ null      ┆ E Chigumb │
│          ┆            ┆         ┆            ┆   ┆           ┆           ┆           ┆ ura       │
└──────────┴────────────┴─────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
matches.filter(pl.col("outcome_result").is_not_null()).head()

shape: (5, 23)
┌──────────┬────────────┬─────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ match_id ┆ start_date ┆ season  ┆ balls_per_ ┆ … ┆ outcome_m ┆ win_by_ru ┆ win_by_wi ┆ player_of │
│ ---      ┆ ---        ┆ ---     ┆ over       ┆   ┆ ethod     ┆ ns        ┆ ckets     ┆ _match    │
│ str      ┆ str        ┆ str     ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆            ┆         ┆ i64        ┆   ┆ str       ┆ i64       ┆ i64       ┆ str       │
╞══════════╪════════════╪═════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1041617  ┆ 2016-08-28 ┆ 2016    ┆ 6          ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1115799  ┆ 2018-01-01 ┆ 2017/18 ┆ 6          ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1123209  ┆ 2018-02-21 ┆ 2017/18 ┆ 6          ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1141835  ┆ 2018-07-29 ┆ 2018    ┆ 6          ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1142504  ┆ 2018-06-17 ┆ 2018    ┆ 6          ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└──────────┴────────────┴─────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [13]:
matches_subset_df = matches.select("match_id", "season", "scheduled_overs", "gender", "team_type",\
    "city", "venue", "team1", "team2", "toss_decision", "outcome_result", "outcome_winner", \
        "win_by_runs", "win_by_wickets", "player_of_match")

In [20]:
matches_subset_df.filter(
    # pl.col("city") == "Delhi",
    # pl.col("gender") == "male",
    # pl.col("scheduled_overs") == 20,
    (
        ((pl.col("team1") == "India") & (pl.col("team2") == "Afghanistan")) |
        ((pl.col("team1") == "Afghanistan") & (pl.col("team2") == "India"))
    )
)

shape: (0, 15)
┌──────────┬────────┬─────────────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ match_id ┆ season ┆ scheduled_o ┆ gender ┆ … ┆ outcome_wi ┆ win_by_run ┆ win_by_wic ┆ player_of_ │
│ ---      ┆ ---    ┆ vers        ┆ ---    ┆   ┆ nner       ┆ s          ┆ kets       ┆ match      │
│ str      ┆ str    ┆ ---         ┆ str    ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│          ┆        ┆ f64         ┆        ┆   ┆ str        ┆ i64        ┆ i64        ┆ str        │
╞══════════╪════════╪═════════════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
└──────────┴────────┴─────────────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [29]:
matches_subset_df.filter(
    ((pl.col("team1")=="India")|(pl.col("team2")=="India")),
    pl.col("gender") == "male"
    )\
    .get_column("team1").unique().to_list()

['India',
 'South Africa',
 'Australia',
 'United Arab Emirates',
 'West Indies',
 'Bangladesh',
 'Pakistan',
 'Namibia',
 'Zimbabwe',
 'New Zealand',
 'Sri Lanka',
 'United States of America',
 'England',
 'Scotland',
 'Ireland']

In [30]:
matches_subset_df.filter(
    ((pl.col("team1")=="India")|(pl.col("team2")=="India")),
    pl.col("gender") == "male"
    )\
    .get_column("team2").unique().to_list()

['Bangladesh',
 'Sri Lanka',
 'Namibia',
 'United States of America',
 'Zimbabwe',
 'England',
 'New Zealand',
 'Australia',
 'India',
 'Ireland',
 'Nepal',
 'South Africa',
 'Oman',
 'Netherlands',
 'Pakistan',
 'United Arab Emirates',
 'Hong Kong',
 'West Indies']

In [32]:
matches_subset_df.filter(
    ((pl.col("team1")=="India")|(pl.col("team2")=="India")),
    pl.col("gender") == "male",
    pl.col("city") == "Delhi"
    )

shape: (5, 15)
┌──────────┬─────────┬────────────┬────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ match_id ┆ season  ┆ scheduled_ ┆ gender ┆ … ┆ outcome_wi ┆ win_by_run ┆ win_by_wic ┆ player_of_ │
│ ---      ┆ ---     ┆ overs      ┆ ---    ┆   ┆ nner       ┆ s          ┆ kets       ┆ match      │
│ str      ┆ str     ┆ ---        ┆ str    ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│          ┆         ┆ f64        ┆        ┆   ┆ str        ┆ i64        ┆ i64        ┆ str        │
╞══════════╪═════════╪════════════╪════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 1120093  ┆ 2017/18 ┆ 20.0       ┆ male   ┆ … ┆ India      ┆ 53         ┆ null       ┆ S Dhawan   │
│ 1187013  ┆ 2019/20 ┆ 20.0       ┆ male   ┆ … ┆ Bangladesh ┆ null       ┆ 7          ┆ Mushfiqur  │
│          ┆         ┆            ┆        ┆   ┆            ┆            ┆            ┆ Rahim      │
│ 1278687  ┆ 2022    ┆ 20.0       ┆ male   ┆ … ┆ South      ┆ null       ┆ 7          ┆ DA Miller  │
│          ┆         ┆            ┆        ┆   ┆ Africa     ┆            ┆            ┆            │
│ 1439894  ┆ 2024/25 ┆ 20.0       ┆ male   ┆ … ┆ India      ┆ 86         ┆ null       ┆ Nithish    │
│          ┆         ┆            ┆        ┆   ┆            ┆            ┆            ┆ Kumar      │
│          ┆         ┆            ┆        ┆   ┆            ┆            ┆            ┆ Reddy      │
│ 1512736  ┆ 2025/26 ┆ 20.0       ┆ male   ┆ … ┆ India      ┆ 93         ┆ null       ┆ HH Pandya  │
└──────────┴─────────┴────────────┴────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [36]:
print(sorted(matches_subset_df.filter(
    pl.col("gender") == "male"
    )\
    .get_column("team1").unique().to_list()))

['Argentina', 'Australia', 'Austria', 'Bahamas', 'Bahrain', 'Bangladesh', 'Belgium', 'Belize', 'Bermuda', 'Bhutan', 'Botswana', 'Brazil', 'Bulgaria', 'Cambodia', 'Cameroon', 'Canada', 'Cayman Islands', 'Chile', 'China', 'Cook Islands', 'Costa Rica', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'England', 'Estonia', 'Eswatini', 'Fiji', 'Finland', 'France', 'Gambia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Guernsey', 'Hong Kong', 'Hungary', 'India', 'Indonesia', 'Iran', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Ivory Coast', 'Japan', 'Jersey', 'Kenya', 'Kuwait', 'Lesotho', 'Luxembourg', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Mexico', 'Mongolia', 'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands', 'New Zealand', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea', 'Peru', 'Philippines', 'Portugal', 'Qatar', 'Romania', 'Rwanda', 'Samoa', 'Saudi Arabia', 'Scotland', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovenia', 'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'St Helena', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Tanzania', 'Thailand', 'Timor-Leste', 'Turkey', 'Turks and Caicos Island', 'Uganda', 'United Arab Emirates', 'United States of America', 'Uzbekistan', 'Vanuatu', 'West Indies', 'Zambia', 'Zimbabwe']